swagger: '2.0'
basePath: /r/insights/platform/aiops-data-collector
paths:
  /api/v0/collect:
    post:
      responses:
        '200':
          description: Success
        '400':
          description: Input payload validation failed
      summary: Endpoint for data collection
      operationId: post_collect
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            $ref: '#/definitions/CollectJSON'
      tags:
        - default
  /:
    get:
      responses:
        '200':
          description: Success
      summary: Root Endpoint
      operationId: get_root
      tags:
      - default
  /api/v0/version:
    get:
      responses:
        '200':
          description: Success
      summary: Endpoint for getting the current version
      operationId: get_version
      tags:
        - default
  /metrics:
    get:
      responses:
        '200':
          description: Success
      summary: Endpoint for Metrics
      operationId: get_metrics
      tags:
      - default
info:
  title: AIOPS Data Collector API
  version: 0.0.1
  description: AIOPS Data Collector API
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: default
    description: Default namespace
definitions:
  CollectJSON:
    required:
      - url
    properties:
      url:
        type: string
        example: 'http://my-url.io'
      payload_id:
        type: string
        example: '123'
    type: object
